### ISSUE TITLE
python implementation of curl command

### ISSUE THREAD

**Issue by shantanuo** [hellohaptik/chatbot_ner#245]
There is a curl command on this page that I am not able execute.
https://github.com/hellohaptik/chatbot_ner/tree/develop/ner_v2/detectors/numeral/number

The curl command is as follows:

 curl -i 'http://'$URL':'$PORT'/v2/number/message=do%20hajaar%20char%20sau&entity_name=number&structured_value=&fallback_value=&bot_message=&min_number_digits=1&max_number_digits=6&source_language=hi&language_script=hi&unit_type='

I will like to know the python implementation of the same.

**Comment by shantanuo** [comment]
I managed this with the following code...

from ner_v2.detectors.numeral.number.number_detection import NumberDetector
detector = NumberDetector(entity_name='number', language='hi')  
detector.detect_entity(text= 'I want char  rs')

But instead of "char" if I am make spelling mistake and type "charr" then I do not get the correct results. For this you need to use hunspell spelling corrections as shown here...

https://github.com/shantanuo/spell_check/blob/master/marthi_numbers_to_text.ipynb

**Comment by chiragjn** [comment]
Thanks for the suggestion, we might consider adding spell correction before starting any detection in the future, but for now, we recommend correcting spellings before calling `detect_entity`. In case such spell mistakes are very common, such variants can also be added directly to the data at

https://github.com/hellohaptik/chatbot_ner/blob/develop/ner_v2/detectors/numeral/number/hi/data/numerals_constant.csv

The primary reason for not supporting this right now is because different languages might need different spell correction strategies and data and we haven't planned out where to train, store and use them in the flow

**Comment by chiragjn** [comment]
Closing this for now
